# Copyright (c) 2026 CoReason Inc.
#
# This software is proprietary and dual-licensed.
# Licensed under the Prosperity Public License 3.0 (the "License").
# A copy of the license is available at https://prosperitylicense.com/versions/3.0.0
# For details, see the LICENSE file.
# Commercial use beyond a 30-day trial requires a separate license.
#
# Source Code: https://github.com/CoReason-AI/coreason_etl_liver_tox

"""XML parsing and text isolation utilities for LiverTox records."""

from typing import Any

import xmltodict

from coreason_etl_liver_tox.utils.logger import logger

# NCBI E-utilities standard tags that can appear as single elements or arrays.
# Forcing them to lists prevents catastrophic schema inference failure downstream.
FORCE_LIST_TAGS = ("sec", "p", "title", "table", "list", "item")


def parse_livertox_xml(xml_bytes: bytes) -> dict[str, Any]:
    """Parse raw XML bytes into a Python dictionary applying stable schema rules.

    AGENT INSTRUCTION: You MUST use force_list with FORCE_LIST_TAGS to guarantee that
    downstream polars/dlt parsing tools do not crash due to scalar vs array mutations.

    Args:
        xml_bytes: The raw XML payload from the NCBI API.

    Returns:
        Dict[str, Any]: The parsed dictionary structure.
    """
    try:
        parsed: dict[str, Any] = xmltodict.parse(
            xml_bytes,
            force_list=FORCE_LIST_TAGS,
            dict_constructor=dict,
        )
        return parsed
    except Exception as e:
        logger.error("Failed to parse LiverTox XML", error=str(e))
        raise ValueError(f"Invalid XML payload: {e}") from e


def _extract_text_from_node(node: str | dict[str, Any] | list[Any] | None) -> str:
    """Recursively extract plain text from an XML dictionary node.

    Args:
        node: A parsed XML node (can be string, dict, list, or None).

    Returns:
        str: The combined plain text.
    """
    if node is None:
        return ""  # pragma: no cover
    if isinstance(node, str):
        return node.strip()  # pragma: no cover
    if isinstance(node, list):
        return " ".join(_extract_text_from_node(child) for child in node if child).strip()  # pragma: no cover
    if isinstance(node, dict):
        # The #text key is generated by xmltodict for text inside tags with attributes
        text_parts = []
        if "#text" in node:
            text_parts.append(str(node["#text"]).strip())  # pragma: no cover

        for key, value in node.items():
            if key.startswith("@") or key == "#text":
                continue  # pragma: no cover
            text_parts.append(_extract_text_from_node(value))

        return " ".join(part for part in text_parts if part).strip()

    return str(node).strip()  # pragma: no cover


def _find_section_by_title(node: Any, target_title: str) -> dict[str, Any] | None:
    """Recursively search the dictionary for a 'sec' containing a matching 'title'.

    Args:
        node: The parsed XML dictionary tree.
        target_title: The title string to match (case-insensitive substring).

    Returns:
        Optional[Dict[str, Any]]: The matching section dictionary, or None if not found.
    """
    if isinstance(node, list):
        for item in node:
            result = _find_section_by_title(item, target_title)
            if result:
                return result  # pragma: no cover
        return None

    if isinstance(node, dict):
        if "sec" in node:
            # force_list ensures 'sec' is a list
            for sec in node["sec"]:
                if "title" in sec:
                    # force_list ensures 'title' is a list
                    for title_node in sec["title"]:
                        title_text = _extract_text_from_node(title_node).lower()
                        if target_title.lower() in title_text:
                            return dict(sec)

                # Recurse into nested sections
                result = _find_section_by_title(sec, target_title)
                if result:
                    return result  # pragma: no cover

        # Check all other keys for nested sections
        for value in node.values():
            result = _find_section_by_title(value, target_title)
            if result:
                return result

    return None


def isolate_hepatotoxicity_summary(record_dict: dict[str, Any]) -> str | None:
    """Traverse the parsed record to isolate the core Hepatotoxicity summary text.

    Args:
        record_dict: The parsed LiverTox XML dictionary.

    Returns:
        Optional[str]: The isolated plain text of the Hepatotoxicity section, or None.
    """
    section = _find_section_by_title(record_dict, "hepatotoxicity")
    if not section:
        return None

    # Exclude the title from the extracted text body
    if "title" in section:
        del section["title"]

    text = _extract_text_from_node(section)
    return text or None


def isolate_likelihood_score(record_dict: dict[str, Any]) -> str | None:
    """Traverse the parsed record to isolate the text block containing the Likelihood score.

    Note: This extracts the raw text block containing the score. The rigorous regex
    extraction of the specific categorical code (e.g., "Category A") is deferred
    to the dbt SQL layer as per the architecture rules.

    Args:
        record_dict: The parsed LiverTox XML dictionary.

    Returns:
        Optional[str]: The isolated plain text containing the Likelihood score, or None.
    """
    # Sometimes likelihood score is its own section, or it's buried in 'Product Information'
    # LiverTox typically has a specific "Likelihood Score" or "Likelihood of Injury" section or paragraph.
    # We will search the entire text space for paragraphs containing "Likelihood score:"

    def _find_likelihood_paragraph(node: Any) -> str | None:
        if isinstance(node, list):
            for item in node:
                res = _find_likelihood_paragraph(item)
                if res:
                    return res  # pragma: no cover
            return None

        if isinstance(node, dict):
            if "p" in node:
                # force_list guarantees 'p' is a list
                for p_node in node["p"]:
                    p_text = _extract_text_from_node(p_node)
                    if "likelihood score:" in p_text.lower():
                        return p_text

            # Check all values recursively
            for value in node.values():
                res = _find_likelihood_paragraph(value)
                if res:
                    return res
        return None

    score_text = _find_likelihood_paragraph(record_dict)
    return score_text or None
